### ISSUE TITLE
I build an online version - might be interesting

### ISSUE THREAD

**Issue by steff-wink** [OWASP/cornucopia#226]
Hi guys,
after a workshop at the OOP 2022 in Germany with the topic of security games, I put together an online version of the cornucopia card game last summer.
It's ugly but somewhat functional, might be interesting to look at for you guys: https://github.com/steff-wink/owasp_cornucopia_online

Or are there other online versions already out there? Haven't seen any so far.
Greetings

**Comment by rewtd** [comment]
There are a couple out there. This is the one I use most often: https://copi.securedelivery.io/

**Comment by steff-wink** [comment]
Wow, either the google gods are leaving me, or it's just hard to find. Looks way better than mine. Thx for the link!
!

**Comment by rewtd** [comment]
Do you mind if I add your link to the project page so folks can see it there too?

**Comment by steff-wink** [comment]
You're most welcome to do so.
